# Finetune the ShapeNet JEPA backbone – fast_dev sanity
ckpt:
  bucket: adlr2025-pointclouds
  backbone_filename: pretrain_pointjepa_epoch=499-step=40500.ckpt
  filename: ""
  extra_epochs: 1

model:
  lr_backbone: 3e-4   # <-- finetune
  lr_head: 3e-3

data:
  root_dir: data/grasp_sample/03948459
  batch_size: 4
  num_workers: 0
  num_points: 1024

trainer:
  fast_dev_run: 3
