# configs/run/local_backbone.yaml
ckpt:
  # point to the file you already have
  backbone_filename: pretrain_pointjepa_epoch=499-step=40500.ckpt

  # no Lightning resume-ckpt for grasp regression itself
  filename: ""

  # you can keep bucket/local_dir; fetch_checkpoint() will see the file exists
  bucket: adlr2025-pointclouds     # kept, but download will be skipped
  local_dir: checkpoints
