name: ADLR
channels:
  - conda-forge
  - defaults
  - pytorch

dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas

  # build tools for C++ extensions
  - cmake
  - ninja
  - pybind11        # <— ADD THIS

  - pip
  - pip:
    - git+https://github.com/facebookresearch/pytorch3d.git@stable
