voxelized_pointcloud:
  voxel_size: 0.05
  dim_mins: null
  dim_maxs: null
  feature_pool_method: "mean"
  limit_voxels: null

feature_slam:
  _target_: preprocessing.unproject_rgbd_feature_slam.UnprojectRGBDFeatureSLAM
  image_feature_generator:
    _target_: preprocessing.image_features.image_embedding.EmbeddingFeatureImageGenerator
    image_feature_encoder:
      _target_: preprocessing.image_features.dino_encoder.DINOV2Encoder
      version: "base"
      device: cuda
    device: cuda
  device: cuda

