# ------------------------------------------------------------
# Base config – shared by every experiment
# ------------------------------------------------------------

# ─── checkpoint settings ────────────────────────────────────
ckpt:
  # Lightning resume-from-checkpoint (leave blank when starting fresh)
  filename: ""
  bucket: adlr2025-pointclouds       # GCS bucket
  local_dir: checkpoints             # local cache dir
  extra_epochs: 2                   # added to epochs parsed from filename
  backbone_filename: pretrain_pointjepa_epoch=499-step=40500.ckpt  # remove for training from scratch

# ─── data module ────────────────────────────────────────────
data:
  root_dir: /mnt/disks/ssd/studentGrasping/student_grasps_v1 # root_dir=data/dlr_hand2, when we load the whole dataset
  ssd_cache_dir: /mnt/disks/ssd/cache      # ← change from /mnt/disks/ssd/cache
  batch_size:    32
  num_workers:   4
  num_points:    1024
  sort_by_score: True
  top_percentile: 0.7

# ─── model hyper-params ────────────────────────────────────
model:
  tokenizer_groups:      64
  tokenizer_group_size:  32
  tokenizer_radius:      0.05

  encoder_dim:           384 # this is fixed by the backbone
  encoder_depth:         12
  encoder_heads:         8
  encoder_dropout:       0.1
  encoder_attn_dropout:  0.1
  encoder_drop_path_rate: 0.1
  encoder_mlp_ratio:     4

  pooling_type:          mean
  pooling_heads:         4
  pooling_dropout:       0.1
  head_hidden_dims:      [512, 256]

  lr_backbone:           0        # 0 = frozen
  lr_head:               3e-3

# ─── trainer args ───────────────────────────────────────────
trainer:
  default_root_dir: artifacts
  accelerator: gpu
  devices: 1
  precision: 16-mixed
  log_every_n_steps: 5
  gradient_clip_val: 1.0
  callbacks:
  - class_path: pytorch_lightning.callbacks.EarlyStopping
    init_args:
      monitor: val_loss
      patience: 10           # stop if no improvement for 5 val epochs
      mode: min
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      monitor: val_loss
      save_top_k: 1
      mode: min
      filename: joint-{epoch:02d}-{val_loss:.4f}
#  - class_path: callbacks.backbone_embedding_inspector.BackboneEmbeddingInspector
#    init_args:
 #     num_batches: 8

# ─── logging ────────────────────────────────────────────────
logger:
  project: adlr
  entity: ADLR2025
  name: joint_regression_mdn

# ─── misc ───────────────────────────────────────────────────
train:
  seed: 42

hydra:
  job:
    chdir: true
