# ─ inherits all keys from train_joint.yaml (or the base you pasted) ─
defaults:
  - train_joint    # or whatever the base file is called
  - _self_

model:
  mdn_mixtures: 10      # number of Gaussian components
  var_min:      1e-3    # variance floor
  beta_entropy: 1e-3    # entropy regulariser weight
  lr_head:      1e-3    # lower LR for MDN head
