ckpt:
  filename: ''
  bucket: adlr2025-pointclouds
  local_dir: checkpoints
  load_backbone: true
  backbone_filename: pretrain_pointjepa_epoch=499-step=40500.ckpt
data:
  preload_all: true
  root_dir: /mnt/disks/ssd
  ssd_cache_dir: /mnt/disks/ssd/cache
  split_file: configs/splits/split_25.json
  batch_size: 32
  num_workers: 4
  num_points: 1024
  score_temp: 0.0
model:
  tokenizer_groups: 64
  tokenizer_group_size: 32
  tokenizer_radius: 0.05
  transformations:
  - none
  coord_change: false
  encoder_dim: 384
  encoder_depth: 12
  encoder_heads: 8
  encoder_dropout: 0.1
  encoder_attn_dropout: 0.1
  encoder_drop_path_rate: 0.1
  encoder_mlp_ratio: 4
  pooling_type: att
  pooling_heads: 4
  pooling_dropout: 0.1
  num_pred: 5
  head_hidden_dims:
  - 512
  - 256
  - 128
  head_dropout: 0.1
  loss_type: min_k_logit
  logit_scale_init: 0.1
  logit_scale_min: 0.01
  logit_scale_max: 6.0
  lr_backbone: 1.0e-05
  lr_head: 0.001
  encoder_unfreeze_epoch: 0
  encoder_unfreeze_step: 0
  weight_decay: 0.02
trainer:
  max_steps: 15000
  check_val_every_n_epoch: null
  val_check_interval: 2500
  limit_val_batches: 1.0
  num_sanity_val_steps: -1
  accelerator: gpu
  devices: 1
  precision: 16-mixed
  default_root_dir: artifacts
  log_every_n_steps: 50
  gradient_clip_val: 1.0
  overfit_batches: 0
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: adlr
  entity: ADLR2025
  group: final_runs
  name: jepa_split25_seed1
  save_code: true
train:
  seed: 1
